export const COLLAPSED_CSS_CLASS = 'collapsed'
export const LEFT_PANE_CSS_ID = 'left-pane'
export const FOLDER_BUTTON_CSS_CLASS = 'folder-button'
export const FOLDER_ARROW_CSS_CLASS = 'folder-arrow'
export const FOLDER_ICON_CSS_CLASS = 'folder-icon'
export const FILE_TABLE_CSS_ID = 'file-table'
export const TABLE_ROW_ITEM_CSS_CLASS = 'table-row-item'
export const TABLE_COL_FILE_NAME_CSS_CLASS = 'col__file-name'
export const FILE_NAME_CSS_CLASS = 'file-name'

export const COLLAPSED_ARROW = '▶'
export const EXPANDED_ARROW = '▼'
export const FILE_ICON = '📄'
export const FOLDER_ICON = '📂'